#!/bin/bash
# Quick script to help download sample loan documents

echo "📋 CrystalTrade - Document Download Helper"
echo "=========================================="
echo ""
echo "Best sources for real loan documents:"
echo ""
echo "1. SEC EDGAR Database (Recommended)"
echo "   URL: https://www.sec.gov/edgar/searchedgar/companysearch.html"
echo "   Search for: Apple Inc, Microsoft, Amazon, etc."
echo "   Filter by: Form Type 8-K"
echo "   Look for: Credit Agreement exhibits"
echo ""
echo "2. Quick Links:"
echo "   - Recent 8-K Filings: https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=8-K"
echo "   - Apple Filings: https://www.sec.gov/cgi-bin/browse-edgar?CIK=AAPL&action=getcompany"
echo "   - Microsoft: https://www.sec.gov/cgi-bin/browse-edgar?CIK=MSFT&action=getcompany"
echo ""
echo "3. Steps:"
echo "   a) Visit SEC EDGAR"
echo "   b) Search for a company"
echo "   c) Filter by 8-K filings"
echo "   d) Find 'Credit Agreement' in title"
echo "   e) Download PDF exhibit"
echo "   f) Save to: backend/uploads/"
echo ""
echo "4. Current uploads folder:"
ls -lh backend/uploads/ 2>/dev/null || echo "   (uploads folder not found)"
echo ""
echo "📖 See DOWNLOAD_TEST_DOCUMENTS.md for detailed instructions"
